# Generated by Django 5.2.5 on 2025-08-24 00:39

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.cover_upload),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
    ]
